name = "StandardPacked"
uuid = "65f29c17-9e56-4606-972f-81e04007695c"
authors = ["Benjamin Desef <projekter-git@yahoo.de>"]
version = "1.0.3"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[weakdeps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Documenter", "Test", "StaticArrays"]

[extensions]
StandardPackedStaticArrays = "StaticArrays"

[compat]
julia = "1.8"
Documenter = "1"
LinearAlgebra = "1"
SparseArrays = "1"
StaticArrays = "1.4.2"
Test = "1"
